language: node_js
node_js:
  - "5"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install
script:
  - npm test
after_success:
  - npm run dist-beanstalk

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: eu-central-1
  bucket: "nfllook-beanstalk"
  skip_cleanup: true
  local_dir: dist
  detect_encoding: true
